SF_WebApi/Controllers/Report/SPPivotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using SF_BusinessLogics.LoginBLL;
using SF_Domain.Inputs;
using SF_Utils;
using SF_WebApi.Models;

namespace SF_WebApi.Controllers.Report
{
    public class SPPivotController : BaseController
    {
        private readonly ILoginBLL _loginbll;

        public SPPivotController(ILoginBLL loginbll)
        {
            _loginbll = loginbll;
        }

        [System.Web.Http.HttpPost]
        [ResponseType(typeof(BaseInput))]
        public IHttpActionResult GetReport(BaseInput inputs)
        {
            var objResponseModel = new ResponseModel();
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var validateAccess = ValidateAuth(inputs.Auth);
            if (!validateAccess)
            {
                objResponseModel.Status = false;
                objResponseModel.Message = EnumHelper.GetDescription(Enums.ResponseType.InternalServerError);
                return Json(objResponseModel);
            }
            var id = Decrypt(inputs.Auth, true);
            var model = _loginbll.CheckMvaUserInfo(id);
            objResponseModel.Status = true;
            objResponseModel.Message = EnumHelper.GetDescription(Enums.ResponseType.Success);
            objResponseModel.Result = GetHost() + "/Report/SPPivot.aspx?p=" + model.rep_position.Replace(" ", string.Empty) + "&n=" + model.rep_id.Replace(" ", string.Empty) + "&s=" + DateTime.Now.ToString("yyyy-MM-dd") + "&e=" + DateTime.Now.ToString("yyyy-MM-dd");
            return Ok(objResponseModel);
        }
    }
}

SF_WebApi/Views/SPPivot/Index.cshtml
@{
    Layout = null;
}

<script type="text/javascript">

    function do_export(s, e) {
        var param = "export;" + s.GetMainElement().getAttribute("type_file");
        SPPivot.PerformCallback({ prm: param });
    }

    function do_retrieve(s, e) {
        //var jsDate = dateEdit.GetDate();
        var jsDateStart = dateStart.GetDate();
        var yearStart = jsDateStart.getFullYear(); // where getFullYear returns the year (four digits)
        var monthStart = jsDateStart.getMonth() + 1; // where getMonth returns the month (from 0-11)
        var dayStart = jsDateStart.getDate();   // where getDate returns the day of the month (from 1-31)

        var jsDateEnd = dateEnd.GetDate();
        var yearEnd = jsDateEnd.getFullYear(); // where getFullYear returns the year (four digits)
        var monthEnd = jsDateEnd.getMonth() + 1; // where getMonth returns the month (from 0-11)
        var dayEnd = jsDateEnd.getDate();   // where getDate returns the day of the month (from 1-31)

        var DateStart = yearStart + '-' + monthStart + '-' + dayStart;
        var DateEnd = yearEnd + '-' + monthEnd + '-' + dayEnd;
        var param = 'retrieve;' + DateStart + ';' + DateEnd;
        //alert(param); return false;
        SPPivot.PerformCallback({ prm: param });

    }
    function do_reset(s, e) {
        dateStart.SetValue(null);
        dateEnd.SetValue(null);
        //cboyear.SetValue(null);
        var param = 'reset;' + null + ';' + null + ';' + null;
        SPPivot.PerformCallback({ prm: param });
        return false;
    }
</script>
<style type="text/css">
    .table {
        width: 100%;
        padding-right: 5px;
        /*border:1px solid red;*/
    }

    .cell-backround {
        background-color: #F0F0F0;
        color: black;
    }

    .cell-newplan {
        padding-top: 4px;
        padding-bottom: 4px;
    }

    .cell-month {
        width: 150px;
        padding-top: 4px;
        padding-bottom: 4px;
        padding-left: 5px;
    }

    .cell-year {
        width: 50px;
        padding-top: 4px;
        padding-bottom: 4px;
        padding-left: 20px;
    }

    .cell-retrieve {
        padding-top: 4px;
        padding-bottom: 4px;
        padding-left: 10px;
    }

    .cell-reset {
        padding-top: 4px;
        padding-bottom: 4px;
        padding-left: 5px;
    }

    .panel-content {
        margin-left: 8px;
        margin-top: 8px;
    }

    .distance-left {
        margin-left: 5px;
    }

    .distance-right {
        margin-right: 5px;
    }

    .cell-blank {
        width: 100%;
        background-color: #F0F0F0;
    }

    .cell-divider {
        height: 5px;
        width: 100%;
    }

    .title-form {
        padding-bottom: 4px;
        background-color: gainsboro;
    }
</style>

<div class="panel-content" style="margin:0px">

    <table class="table" style="margin:0px">
        <tr><td class="title-form" style="text-align:center; font-weight:bold;" colspan="11">:: SALES PROMOTION PIVOT ::</td></tr>
        <tr>
            <td class="cell-month cell-backround">
                @Html.DevExpress().DateEdit(
                    settings => {
                        settings.Name = "dateStart";
                                    settings.Properties.Caption = "Date Start";
                                    settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                                    settings.Name = "dateStart";
                                    settings.Properties.NullText = "Date Start";
                    }).GetHtml()
                
                </td>
            <td class="cell-month cell-backround">
                @Html.DevExpress().DateEdit(
                    settings => {
                                    settings.Name = "dateEnd";
                                    settings.Properties.Caption = "Date End";
                                    settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Left;
                                    settings.Name = "dateEnd";
                                    settings.Properties.NullText = "Date End";
                    }).GetHtml()
                
            </td>
            <td class="cell-reset cell-backround">

                @Html.DevExpress().Button(
                    settings =>
                    {
                        settings.Name = "btnreset";
                        settings.UseSubmitBehavior = true;
                        settings.ControlStyle.CssClass = "button";
                        settings.Text = "Reset";
                        settings.Images.Image.Url = "~/Content/Images/reset.png";
                        settings.ToolTip = "Reset";
                        settings.ClientSideEvents.Click = "do_reset";
                    }
                    ).GetHtml()
            </td>
            <td class="cell-blank"></td>
            <td class="cell-blank"></td>
            <td class="cell-reset cell-backround"></td>
            <td class="cell-reset cell-backround"></td>
            <td class="cell-reset cell-backround">
                @Html.DevExpress().Button(
                    settings =>
                    {
                        settings.Name = "btnretrieve";
                        settings.ControlStyle.CssClass = "button";
                        settings.Text = "Retrieve";
                        settings.Images.Image.Url = "~/Content/Images/retrieve.png";
                        settings.ToolTip = "Retrieve";
                        settings.ClientSideEvents.Click = "do_retrieve";
                    }
                ).GetHtml()
            </td>
            <td class="cell-reset cell-backround">

                @Html.DevExpress().Button(
                settings =>
                {
                    settings.Name = "PDF";
                    settings.ControlStyle.CssClass = "button";
                    settings.Text = "Export to PDF";
                    settings.Images.Image.Url = "~/Content/Images/pdf.png";
                    settings.ToolTip = "Export to PDF";
                    settings.Attributes["type_file"] = "PDF";
                    settings.UseSubmitBehavior = true;
                    settings.ClientSideEvents.Click = "do_export";
                }
            ).GetHtml()


            </td>

            @*<td class="cell-retrieve cell-backround">
                @Html.DevExpress().DateEdit(
                    settings => {
                        settings.Name = "btnretrieve";
                                    settings.ControlStyle.CssClass = "button";
                                    settings.Text = "Retrieve";
                                    settings.Images.Image.Url = "~/Content/Images/retrieve.png";
                                    settings.ToolTip = "Retrieve";
                                    settings.ClientSideEvents.Click = "do_retrieve";
                    }).GetHtml()

            </td>
                <td class="cell-reset cell-backround">
                    @Html.DevExpress().Button(Sub(settings)
                                                  settings.Name = "btnreset"
                                                  settings.UseSubmitBehavior = True
                                                  settings.ControlStyle.CssClass = "button"
                                                  settings.Text = "Reset"
                                                  settings.Images.Image.Url = "~/Content/Images/reset.png"
                                                  settings.ToolTip = "Reset"
                                                  settings.ClientSideEvents.Click = "do_reset"
                                              End Sub).GetHtml()
                </td>
                <td class="cell-blank"></td>
                <td class="cell-blank"></td>
                <td class="cell-reset cell-backround"></td>
                <td class="cell-reset cell-backround"></td>
                <td class="cell-reset cell-backround">
                    @Html.DevExpress().Button(Sub(settings)
                                                  settings.Name = "PDF"
                                                  settings.ControlStyle.CssClass = "button"
                                                  settings.Text = "Export to PDF"
                                                  settings.Images.Image.Url = "~/Content/Images/pdf.png"
                                                  settings.ToolTip = "Export to PDF"
                                                  settings.Attributes("type_file") = "PDF"
                                                  settings.UseSubmitBehavior = True
                                                  settings.ClientSideEvents.Click = "do_export"
                                              End Sub).GetHtml()
                </td>
                <td class="cell-reset cell-backround">
                    @Html.DevExpress().Button(Sub(settings)
                                                  settings.Name = "RawData"
                                                  settings.ControlStyle.CssClass = "button"
                                                  settings.Text = "Export Row Data"
                                                  settings.Images.Image.Url = "~/Content/Images/pdf.png"
                                                  settings.ToolTip = "Export Row Data"
                                                  settings.Attributes("type_file") = "ROWDATA"
                                                  settings.UseSubmitBehavior = True
                                                  settings.ClientSideEvents.Click = "do_export"
                                              End Sub).GetHtml()
                </td>
                <td class="cell-reset cell-backround">
                    @Html.DevExpress().Button(Sub(settings)
                                                  settings.Name = "XLS"
                                                  settings.ControlStyle.CssClass = "button"
                                                  settings.Text = "Export to Excell"
                                                  settings.Images.Image.Url = "~/Content/Images/excel.png"
                                                  settings.ToolTip = "Export to Excell"
                                                  settings.ControlStyle.CssClass = "distance-right"
                                                  settings.Attributes("type_file") = "XLS"
                                                  settings.UseSubmitBehavior = True
                                                  settings.ClientSideEvents.Click = "do_export"
                                              End Sub).GetHtml()
                </td>*@
        </tr>
    </table>

    <table style="width:100%;">
        <tr>
            <td style="padding-top:0px;vertical-align:top;">
                @*@Html.Action("SPPivotView", Model)*@
                @Html.Action("PivotGrid1Partial", "SPPivot")
            </td>
            <td style="width:300px">
                @Html.DevExpress().PivotCustomizationExtension(SF_WebApi.Controllers.Report.SPPivotGridLayout.SPPivotGridSettings).GetHtml()
            </td>
        </tr>
    </table>
</div>

SF_WebApi/Views/SPPivot/_PivotGrid1Partial.cshtml
@Html.DevExpress().PivotGrid(SF_WebApi.Controllers.Report.SPPivotGridLayout.SPPivotGridSettings).Bind(Model).GetHtml()
@*@Html.DevExpress().PivotGrid(settings =>
{
    settings.Name = "PivotGrid1";
    settings.CallbackRouteValues = new {Controller = "SPPivot", Action = "PivotGrid1Partial"};

    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.RowArea;
        field.FieldName = "sp_id";
        field.Caption = "sp_id";
        field.AreaIndex = 1;
        field.ID = "1";
        field.Visible = false;
        field.Index = 0;
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.RowArea;
        field.FieldName = "spr_id";
        field.Caption = "spr_id";
        field.ID = "2";
        field.Visible = false;
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "spr_no";
        field.Caption = "spr_no";
        field.ID = "3";
        field.Visible = false;
    });
    
    settings.Fields.Add(field =>
    {
        field.ID = "4";
        field.Area = PivotArea.RowArea;
        field.FieldName = "sp_type";
        field.Caption = "sp_type";
        field.Visible = true;
        field.AreaIndex = 0;
        field.Index = 3;
    });
    settings.Fields.Add(field =>
    {
        field.ID = "58";
        field.Area = PivotArea.RowArea;
        field.FieldName = "e_name";
        field.Caption = "EVENT NAME";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.RowArea;
        field.FieldName = "e_topic";
        field.Caption = "e_topic";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "e_place";
        field.Caption = "e_place";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "e_dt_start";
        field.Caption = "e_dt_start";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "e_dt_end";
        field.Caption = "e_dt_end";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "date_realization";
        field.Caption = "date_realization";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "product";
        field.Caption = "product";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "sponsor";
        field.Caption = "sponsor";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "dr_code";
        field.Caption = "dr_code";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "dr_name";
        field.Caption = "dr_name";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "sp_product_ownership";
        field.Caption = "sp_product_ownership";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.Visible = false;
        field.FieldName = "o_description";
        field.Caption = "o_description";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "count_sp_plan";
        field.Caption = "count_sp_plan";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "count_sp_real";
        field.Caption = "count_sp_real";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.DataArea;
        field.FieldName = "count_dr_plan";
        field.Caption = "DR PLAN";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.DataArea;
        field.FieldName = "count_dr_real";
        field.Caption = "count_dr_real";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.DataArea;
        field.FieldName = "budget_plan_value";
        field.Caption = "budget_plan_value";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.DataArea;
        field.FieldName = "budget_real_value";
        field.Caption = "budget_real_value";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "initiator_name";
        field.Caption = "initiator_name";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "rep_name";
        field.Caption = "rep_name";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "rep_sbo";
        field.Caption = "rep_sbo";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "rep_bo";
        field.Caption = "rep_bo";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "rep_region";
        field.Caption = "rep_region";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "nama_am";
        field.Caption = "nama_am";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "nama_rm";
        field.Caption = "nama_rm";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "nama_ppm";
        field.Caption = "nama_ppm";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "dr_spec";
        field.Caption = "dr_spec";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "dr_sub_spec";
        field.Caption = "dr_sub_spec";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "dr_quadrant";
        field.Caption = "dr_quadrant";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "dr_monitoring";
        field.Caption = "dr_monitoring";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "spr_status";
        field.Caption = "spr_status";
    });
    settings.Fields.Add(field =>
    {
        field.Area = PivotArea.FilterArea;
        field.FieldName = "sp_status";
        field.Caption = "sp_status";
    });
}).Bind(Model).GetHtml()*@